[package]
name = "xhype"
version = "0.1.0"
authors = ["Changyuan Lyu <changyuanl@google.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
log = "0.4"
env_logger = "0.7.1"
lazy_static = "1.4.0"

[build-dependencies]
cc = "1.0.46"

[features]
vthread_closure = []
virtio_mmio_legacy = []